/* Student Name: Chenyu Yao (Dominic)                               Simon Game
 * Student #: 38186145
 * Lab section: L2J
 * UBC Email: dominicycy@alumni.ubc.ca
 * 
 * Purpose: This program implements the Simon Game in C using the DAQ simulator
 *          For more detailed info for Simon Game, see " http://en.wikipedia.org/wiki/Simon_(game) "
 */


#define _CRT_SECURE_NO_WARNINGS

#include <stdio.h>
#include <stdlib.h>
#include <DAQlib.h>
#include <Windows.h>
#include <time.h>

const int GREEN = 0,
	      RED = 1,
		  YELLOW = 2,
		  BLUE = 3,
		  ON = 1, 
		  OFF = 0,
		  MAX_LEN = 5,  
		  FLASH = 300,
		  NEXT_ROUND = 1000;


void  runSimon (void);
 int  randInt( int lower, int upper );
void  generateSequence(int length, int data[]);
void  playSequence (int length, int data[] );
 int  checkInput (void);
void  flashingLED( int Led, int interval );
void  endingFlash (int channelNum);
void  printArray (int Length, int data[]);


int main () {
	int setupNUM;

	printf( "Enter the DAQ device number, 0 for hardware, 6 for Simon Game simulator: " );
	scanf( "%d", &setupNUM );

	if( setupDAQ( setupNUM ) ){
		printf( "GAME START~\n");
		runSimon();
	} else{
		printf( "Failed to initialize DAQ device...please reopen it\n" );
	}

	system( "PAUSE" );
	return 0;

}



/* This is the main work function runSimon.

 * Everytime before starting a new sequence (next round) or before restaring the game,
   the red, yellow and green leds will flash in order of "red, yellow, green", to allow users to get ready.
   In the meantime, it will also print "3 2 1 let's start!" on the screen.

 * It will also print out the random sequence it has generated each time. Well, you can cheat by that actually... but that is no the point, it just makes things clear.
   It wll also record the player's input and prints them out at the same time.
 * The printing format of both sequence (the one generated by computer and the one read from the playr) 
   are like :"[idx]-value   ". All of these additionals are for the convenience for whoever testing this program later.
 
 * Moreover, a statement "if(!continueSuperLoop()) {break;}" are inserted at somewhere within the code. 
   This will make the program being reaponsive and terminate itself anytime the player quits the game.
   
 
 */
void runSimon (void){
	 int output[20]; 
	 int input[20];
     int N;
	 int idx;

	while( continueSuperLoop() ){
		N = 1;
	     
		while (N <= MAX_LEN){
			srand( (unsigned) time( NULL ) );

			/* The followig segment of code is to to allow some short time before the game starts/restarts to get the player ready.*/
			Sleep(NEXT_ROUND);
			printf( "\n3 ");
			flashingLED(RED, NEXT_ROUND);
			if(!continueSuperLoop()) {break;}
			
			Sleep(NEXT_ROUND);
			printf( "2 ");
			flashingLED(YELLOW, NEXT_ROUND);
			if(!continueSuperLoop()) {break;}

			Sleep(NEXT_ROUND);
			printf( "1 ");
			flashingLED(GREEN, NEXT_ROUND);
			if(!continueSuperLoop()) {break;}

			printf( "Let's start!\n" );
			Sleep(NEXT_ROUND);
			if(!continueSuperLoop()) {break;}
			/* The end of the preperation
			*/

			
			generateSequence(N, output );

			printf( "\nThe currently generated sequence are:\n");
			printArray( N, output);
			printf( "\n" );
			if(!continueSuperLoop()) {break;}

			playSequence(N, output );
			if(!continueSuperLoop()) {break;}
		
			idx = 0;

			printf( "What are those LEDs that are turned on just now?:\n");
			/* begin to read the player's inputs and compare them with the generated sequence early */
			while (idx < N ){

				input[idx] = checkInput();
				if(!continueSuperLoop()) {break;}

				printf( "[%d]-%d  ", idx, input[idx] ); 
			
				/*check if the player's input is the same as the output from the computer, 
				 if not, break from the current loop*/
				if( input[idx] != output[idx] ){
					break; 
				} else{
					idx++;
				}

			}
			
			/*if the above loop is break because the user pressed all right buttons, idx will equal to N,
			which will larger than the actual last idx by 1 due to the "idx++" at the end.
			so we will minus idx so that the following comparisons will work*/
			if (idx = N){
				idx--;
			}

			/*check if the break of the above loop is because of the player pressing the wrong button (made a mistake)
			If so, break from this loop as well to start a new game.*/
			if( input[idx] != output[idx] ){
				break;
			}

			/* If not, it means the player got all the answers right, go to next round in current game (within current loop) */
			if(!continueSuperLoop()) {break;}		
			printf("\nGood job, Keep going...\nNext round is coming...\n" );
			N++;       
		}
		if(!continueSuperLoop()) {break;}
		

		/* the following code is to check again whether the reason of ending the game is 
		  that the player made a mistake or that the player wins, and prints out proper messages on the screen*/
		if( input[idx] != output[idx] ){
			printf("\nYOU LOSE :-( \n" );
			endingFlash(RED);	
			printf(".... Restarting the game...\n");
			if(!continueSuperLoop()) {break;}
		}
		else{
			printf( "\nYOU WIN :-D !\n");
			endingFlash(GREEN);
			printf("BE READY TO ANOTHER ROUND!\n");
			if(!continueSuperLoop()) {break;}
		}

	}

	printf("\nThanks for playing :D ! See you next time!\n\n" );

}



/* Function: randInt
 * Purpose: generate random numbers between the lower value and the upper value  (including lower value but excluding the upper value)
 */
int randInt( int lower, int upper ){
	int Num;
	
	do{
		Num = rand() % upper;
	}while( Num < lower );

	return Num;
}


/* Function generateSequence
 * Purpose: generate a random sequence of a given length and store it in the array */
void generateSequence(int length, int data[]){
	int i;

	for( i = 0; i < length; i ++){
		data[i] = randInt(0, 4);
	}
}



/* Function: playSequence
 * Purpose:  display a sequence of colors on DAQ module in a order that corresponds to the given sequence (array)
 */
void playSequence (int length, int data[] ){
	int i;

	for( i = 0; i < length; i ++){
		flashingLED( data[i], FLASH );
		Sleep( FLASH );

	}
}


/* Function: checkInput
 * Purpose: Check which push button is being pressed by player, and return the channel number of that button.
 *          It also make the LED dislay response to the player: 
            As long as the play are pressing the button, the correspondig LED is on; 
			As soon as players release the button, the corresponding LED will be off.
 */
int checkInput (void){
	int button;
	int push = FALSE;
	
	/*Here uses while( continueSuperLoop() ) 
	 so that the program will stop trying to read the channel number of the button when the simulator are off */
	while( continueSuperLoop()){
		button = 0;

		/* This loop will continue to check all the push-buttons untill one of them is found to be on (to be pressed)*/
     	while( button < 4){
			/* As long as player is pressing the button (switch), the corresponding LED will be on.( it is trapped in this loop)*/
		    while( digitalRead(button) == ON ){
				push = TRUE;
				digitalWrite(button, ON);
			}
	        			
			if( push ){
				digitalWrite(button, OFF);
				return button;	
			}

			button ++;
		}
	}
	return button;
	/*This step will only happen when player quit the game, then the button value returned here actaully will never be used.*/

}



/* Function:   flashingLED
 * Purpose:    Turn on and then turn off a particular LED at a given time interval.
 */
void  flashingLED( int Led, int interval ){
	digitalWrite(Led, ON);
	Sleep(interval);
	digitalWrite(Led, OFF);

}

/* Function: endingFlash
 * Purpose:  flash the particular LED of the given channel number for three times
 */
void endingFlash (int channelNum){

			flashingLED(channelNum, FLASH);
			Sleep(FLASH);
			flashingLED(channelNum, FLASH);
			Sleep(FLASH);
			flashingLED(channelNum, FLASH);
			Sleep(FLASH);

}


/* Funtion: printArray
 * Purpose: print out the elements in a given array in the format like this: " [idx]-value   " */
void printArray (int Length, int data[]){
	int i = 0;

	while( i < Length ){
		printf( "[%d]-%d  ", i,data[i] );
		i++;
	}
}






